/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-Modulos_L1A
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_MODULOS_L1A_API_H
#define INCLUDED_MODULOS_L1A_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_Modulos_L1A_EXPORTS
#define MODULOS_L1A_API __GR_ATTR_EXPORT
#else
#define MODULOS_L1A_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_MODULOS_L1A_API_H */
